
identifier: "testing"

rabbitmq:
  host: "192.168.99.100"
  port: 32779
  username: guest
  password: guest
  queues:
    messages: messages
    events: events
    channels: channels

services:
  mixer:
    id: ""
    secret: ""
